config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    omniauth_callbacks: "users/omniauth_callbacks"
  }
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"

  resources :shows, only:[:show, :index]

  resources :selected_shows, only:[:index, :show, :create, :destroy]

  resources :playlists, only:[:index, :show, :new, :create, :destroy]

  resources :songs, only:[:show, :index, :create]

  resources :playlist_songs, only:[:create]

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/playlist.rb
class Playlist < ApplicationRecord
  belongs_to :user
  has_many :playlist_songs, dependent: :destroy
  has_many :songs, through: :playlist_songs, dependent: :destroy

  validates :name, presence: true
end

app/models/playlist_song.rb
class PlaylistSong < ApplicationRecord
  belongs_to :playlist
  belongs_to :song
end

app/models/selected_show.rb
class SelectedShow < ApplicationRecord
  belongs_to :user
  belongs_to :show
end

app/models/show.rb
class Show < ApplicationRecord
  has_many :songs
  has_many :reviews
  has_many :selected_shows, dependent: :destroy
  has_many :users, through: :selected_shows

  validates :title, :description, :image_url, presence: true
end

app/models/song.rb
class Song < ApplicationRecord
  before_destroy :delete_associated_playlist_songs

  belongs_to :show

  has_many :playlist_songs
  has_many :playlists, through: :playlist_songs

  validates :title, presence: true

  private

  def delete_associated_playlist_songs
    playlist_songs.each(&:destroy)
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :omniauthable, omniauth_providers: %i[spotify]

  has_many :playlists
  has_many :selected_shows
  has_many :shows, through: :selected_shows

  validates :first_name, :last_name, presence: true

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.first_name = auth.info['first_name'] || 'DefaultFirstName'
      user.last_name = auth.info['last_name'] || 'DefaultLastName'
      user.email = auth.info['email'] || 'example@example.com'
      user.password = Devise.friendly_token[0, 20]
    end.tap do |user|
      user.save! if user.persisted?
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :home ]

  def home
  end
end

app/controllers/playlist_songs_controller.rb
class PlaylistSongsController < ApplicationController
  def create
    @playlist_song = PlaylistSong.new(params_playlist_song)
    if @playlist_song.save
      redirect_to playlist_path(@playlist_song.playlist)
    else
      render json: { errors: @playlist_song.errors.full_messages }, status: :unprocessable_entity
    end
  end

  private

  def params_playlist_song
    params.require(:playlist_song).permit(:song_id, :playlist_id)
  end
end

app/controllers/playlists_controller.rb
class PlaylistsController < ApplicationController
  def index
    @playlists = Playlist.all
    @playlist = Playlist.new
  end

  def show
    @playlist = Playlist.find(params[:id])
    @playlist_songs = PlaylistSong.where(playlist_id: @playlist.id)
  end

  def new
    @playlist = Playlist.new
  end

  def create
    @playlist = Playlist.new(params_playlist)
    if @playlist.save
      redirect_to playlist_path(@playlist), notice: 'New Playlist created.'
    else
      render json: { errors: @playlist.errors.full_messages }, status: :unprocessable_entity
    end
  end

  def destroy
    @playlist = Playlist.find(params[:id])
    @playlist.destroy
    redirect_to playlists_path, notice: "Playlist successfully deleted!"
  end

  private

  def params_playlist
    params.require(:playlist).permit(:user_id, :name)
  end
end

app/controllers/selected_shows_controller.rb
class SelectedShowsController < ApplicationController
  def index
    @selected_shows = SelectedShow.all
  end

  def show
    @selected_show = SelectedShow.find(params[:id])
    @songs = @selected_show.show.songs
    @albums = RSpotify::Album.search(@selected_show.show.title).first(1)
    @playlist_song = PlaylistSong.new
    @playlist = Playlist.new
  end

  def create
    @selected_show = SelectedShow.new(params_selected_show)
    if @selected_show.save
      redirect_to selected_shows_path, notice: 'This show was successfully added to your faves.'
    else
      render json: { errors: @selected_show.errors.full_messages }, status: :unprocessable_entity
    end
  end

  def destroy
    @selected_show = SelectedShow.find(params[:id])
    @selected_show.destroy
    redirect_to selected_shows_path, notice: "Show successfully removed from your faves!"
  end

  private

  def params_selected_show
    params.require(:selected_show).permit(:user_id, :show_id)
  end

end

app/controllers/shows_controller.rb
class ShowsController < ApplicationController

  def show
    @show = Show.find(params[:id])
  end

  def index
    RSpotify.authenticate(ENV["SPOTIFY_CLIENT_ID"], ENV["SPOTIFY_CLIENT_SECRET"])

    if params[:search].present?
      query = params[:search].capitalize
      @shows = Show.where("title LIKE ?", "%#{query}%")
    else
      @shows = Show.all
    end
  end
end

app/controllers/songs_controller.rb
class SongsController < ApplicationController
  def index

  end

  def show
    @song = Song.find(params[:id])
  end

  def create
    @playlist_song = PlaylistSong.new
    @song = Song.new(params_song)
    if @song.save
      render "songs/_playlist_song_modal"
    else
      render json: { errors: @playlist.errors.full_messages }, status: :unprocessable_entity
    end
  end

  private

  def params_song
    params.require(:song).permit(:show_id, :title, :image_url, :track_id, artists:[])
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  skip_before_action :verify_authenticity_token, only: :spotify

  def spotify
    @user = User.from_omniauth(request.env["omniauth.auth"])
    if @user.persisted?
      @user.update(
        access_token: request.env["omniauth.auth"].credentials.token,
        refresh_token: request.env["omniauth.auth"].credentials.refresh_token
      )
      sign_in @user, event: :authentication
      set_flash_message(:notice, :success, kind: "Spotify") if is_navigational_format?
      redirect_to shows_path
    else
      session["devise.spotify_data"] = request.env["omniauth.auth"].except(:extra)
      redirect_to new_user_registration_url
    end
  end

  def passthru
    redirect_to root_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BroadwayBeats</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="icon" type="image/ico" href="<%= asset_path('favicon.ico') %>">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Poppins:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap" rel="stylesheet">
  </head>
  <body>
    <% unless current_page?(root_path) %>
      <%= render "shared/header" %>
    <% end %>


    <%= render "shared/flashes" %>

    <%= yield %>

    <%= render "shared/navbar" %>



  </body>
</html>

app/views/pages/home.html.erb
<div class="login-btns d-flex flex-column justify-content-center align-items-center mt-3">
  <% if user_signed_in? %>
     <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item", class:"btn btn-app homepage" %>
  <% else %>
    <%= link_to "Sign up with Spotify",  user_spotify_omniauth_authorize_path(show_dialog: true), class:"btn btn-app homepage" , data: { 'turbo-method' => :post } %>
  <% end %>
</div>

<video autoplay muted id="background-video">
  <source src="https://files.catbox.moe/840tm0.mp4" type="video/mp4">
</video>

app/views/playlists/_new.html.erb
<div class="container my-3">

  <%= simple_form_for @playlist do |f| %>
    <%= f.input :name %>
    <%= f.hidden_field :user_id, value: current_user.id %>
  <%= f.submit class:"btn-app", value: "Create playlist"%>
<% end %>
</div>

app/views/playlists/index.html.erb
<div class="container">
  <h2 class="text-center">My Playlists</h2>
    <div class="playlists-container m-3 d-flex align-items-center justify-content-between">
      <% @playlists.each do | playlist | %>
        <div class="playlist-card my-3">
          <%= link_to playlist.name, playlist_path(playlist) %>
        </div>
        <%= link_to playlist_path(playlist), data: { turbo_confirm: "Are you sure?", turbo_method: :delete } do %>
          <i class="fa-solid fa-heart-crack"></i>
        <% end %>
      <% end %>
    </div>
    <%= render "playlists/new" %>
</div>

app/views/playlists/show.html.erb
<div class="container" data-controller="music-player">
  <div id="access-token" data-token="<%= current_user.access_token %>"></div>
  <h3 class="text-center"><%= @playlist.name %></h3>
    <% @playlist_songs.each do | playlist_song | %>
      <div class="track p-3">
        <div class="d-flex align-items-center">
          <div>
            <%= image_tag playlist_song.song.image_url, class:"avatar-square playlist-img", data: { music_player_target: "imagePlaylist" }%>
          </div>
          <div>
            <%= playlist_song.song.title %>
            <div class="artists-container d-flex">
            <% playlist_song.song.artists.first(2).each_with_index do |artist, index| %>
            <p class="artist-name"><%= ",  " if index > 0 %> <%= artist %></p>
            <% end %>
          </div>
          </div>
        </div>
        <button class="play-button start-track " data-music-player-target="playButtons"  data-action="click->music-player#playlist" data-album-track-id="<%= playlist_song.song.track_id %>" data-track-name-id="<%= playlist_song.song.title%>" data-track-url-id="<%= playlist_song.song.image_url%>"  ><i class="fa-solid fa-play playlist-btn"></i></button>

        <div class="player-container d-flex justify-content-between align-items-center d-none"  data-music-player-target="player" >
          <div class ="track-playing w-75 d-flex align-items-center p-3" data-music-player-target="divTrackPlaying">

          </div>
          <button class="play-btn" data-playing="false" ><i class="fa-solid fa-play"></i></button>
        </div>
      </div>
    <% end %>
</div>

<script src="https://sdk.scdn.co/spotify-player.js"></script>
<script>
   if (sessionStorage.getItem('pageLoadedBefore')) {
  // If so, reload the page
  sessionStorage.removeItem('pageLoadedBefore');
  window.location.reload();
} else {
  // If not, set the flag in sessionStorage
  sessionStorage.setItem('pageLoadedBefore', true);
}

  document.addEventListener('DOMContentLoaded', function() {
  let player;
  let playbackPosition;

  // Function to play track
  function playTrack(trackId) {
    const token = document.getElementById("access-token").dataset.token;
    player = new Spotify.Player({
      name: 'Web Playback SDK Quick Start Player',
      getOAuthToken: cb => { cb(token); },
      volume: 0.5
    });

    // Play the track
    player.addListener('ready', ({ device_id }) => {
      console.log('Ready with Device ID', device_id);
      playTrackOnDevice(device_id, trackId);
    });

    player.connect();
  }

  // Function to play track on the device
  function playTrackOnDevice(deviceId, trackId) {
    const token = document.getElementById("access-token").dataset.token;
    fetch(`https://api.spotify.com/v1/me/player/play?device_id=${deviceId}`, {
      method: 'PUT',
      body: JSON.stringify({
        uris: [`spotify:track:${trackId}`],
        position_ms: playbackPosition
      }),
      headers: {
        'Content-Type': 'application/json',
        'Authorization': `Bearer ${token}`
      },
    });
  }

  // Function to pause track
  function pauseTrack() {
    player.getCurrentState().then(state => {
      if (state) {
        playbackPosition = state.position;
        player.pause();
      }
    });
  }

  // Define a global variable to store the currently playing track ID
let currentlyPlayingTrackId = null;


// Event listener for play/pause button
const playButton = document.querySelector('.play-btn');
playButton.addEventListener('click', function() {
  const trackId = document.querySelector(".track-title-player").dataset.albumTrackId;
  const isPlaying = this.dataset.playing === 'true';

  // Check if the current track is already playing
  const isCurrentTrackPlaying = trackId === currentlyPlayingTrackId;

  if (isPlaying) {
    // Pause the track only if it's the currently playing track
    if (isCurrentTrackPlaying) {
      pauseTrack();
    }
    this.dataset.playing = 'false';
    this.innerHTML = '<i class="fa-solid fa-play"></i>';
  } else {
    // Play the track from the beginning if it's a new track
    if (!isCurrentTrackPlaying) {
      playbackPosition = 0; // Start from the beginning
    }
    playTrack(trackId);
    currentlyPlayingTrackId = trackId; // Update currentlyPlayingTrackId
    this.dataset.playing = 'true';
    this.innerHTML = '<i class="fa-solid fa-pause"></i>';
  }
});


  // Spotify Web Playback SDK initialization
  window.onSpotifyWebPlaybackSDKReady = () => {
    const token = document.getElementById("access-token").dataset.token;
    player = new Spotify.Player({
      name: 'Web Playback SDK Quick Start Player',
      getOAuthToken: cb => { cb(token); },
      volume: 0.5,
      robustnessLevel: 'MID'

    });

    // Ready
    player.addListener('ready', ({ device_id }) => {
      console.log('Ready with Device ID', device_id);
    });

    // Not Ready
    player.addListener('not_ready', ({ device_id }) => {
      console.log('Device ID has gone offline', device_id);
    });

    player.addListener('initialization_error', ({ message }) => {
      console.error(message);
    });

    player.addListener('authentication_error', ({ message }) => {
      console.error(message);
    });

    player.addListener('account_error', ({ message }) => {
      console.error(message);
    });

    player.connect();
  };
});
</script>

app/views/selected_shows/index.html.erb
<h2 class="text-center">My Favorite Shows</h2>

<div class="cards-container mb-3">
  <% @selected_shows.each do | selected_show | %>
    <div class="card-show d-flex p-3 justify-content-between">
      <%= link_to selected_show_path(selected_show) do %>
        <div class="card-img w-50">
          <%= image_tag selected_show.show.image_url %>
        </div>
        <div class="card-info w-50">
          <div class="card-title d-flex justify-content-between">
            <h3><strong><%= selected_show.show.title %></strong></h3>
            <%= link_to selected_show_path(selected_show), data: { turbo_confirm: "Are you sure?", turbo_method: :delete } do %>
              <i class="fa-solid fa-heart-crack"></i>
            <% end %>
          </div>
          <div class="card-description d-flex flex-column">
            <%= selected_show.show.description.truncate(80, separator: ' ', omission: '...') %>
            <%= link_to selected_show_path(selected_show) do %>
              <i class="fa-solid fa-headphones"></i>
            <% end %>
          </div>
        </div>
      <% end %>
    </div>
  <% end %>
</div>

app/views/selected_shows/show.html.erb
<div data-controller="modal" >
  <div class="card-container d-flex flex-column">
    <div id="access-token" data-token="<%= current_user.access_token %>"></div>
    <div class="show-title text-center">
      <h2><%= @selected_show.show.title %></h2>
    </div>
    <div class="show-img my-3 ">
      <%= image_tag @selected_show.show.banner_url %>
    </div>
    <div class="show-description p-3">
      <%= @selected_show.show.description %>
    </div>
    <div class="show-album p-3 mb-5">
      <% @albums.each do |album| %>
        <p><strong><%= album.name %></strong></p>
        <div class="show-album-img text-center">
          <%= image_tag album.images.first['url'], class: "avatar-large my-3" %>
        </div>
        <div class="show-album-tracks" data-controller="music-player" >
          <% @songs.each do |track| %>
            <div class="track">
              <%= track.title %>
              <button type="button" class="btn btn-link" data-bs-toggle="modal" data-bs-target="#songModal" data-modal-target="modal" data-action="click->modal#showModal" data-track-id="<%= track.id %>" data-track-title="<%= track.title %>">
                <i class="fa-regular fa-heart heart-songs"></i>
              </button>

              <button class="play-button start-track" data-music-player-target="playButtons"  data-action="click->music-player#play" data-album-track-id="<%= track.track_id %>" data-track-name-id="<%= track.title %>"><i class="fa-solid fa-play" ></i></button>
              <div class="artists-container d-flex">
                <% track.artists.first(2).each_with_index do |artist, index| %>
                  <p class="artist-name"><%= ",  " if index > 0 %> <%= artist %></p>
                <% end %>
              </div>
              <div class="player-container d-flex justify-content-between align-items-center d-none"  data-music-player-target="player" >
                <div class ="track-playing w-75 d-flex align-items-center p-3" data-music-player-target="divTrackPlaying">

                </div>
                <button class="play-btn" ><i class="fa-solid fa-play"></i></button>
              </div>
            </div>
          <% end %>
        </div>
      <% end %>
    </div>
  </div>



  <div class="modal" id="songModal" tabindex="-1" aria-labelledby="songModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <% if current_user.playlists.present? %>
        <div class="new-playlist">
          <div class="modal-header text-center">
            <p class="modal-song-title w-75"><span id="modalSongTitle" data-modal-target="title"></span> </p>
            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
          </div>
          <div class="modal-body">
            <%= simple_form_for @playlist_song, id: "playlistSongForm" do |f| %>
              <%= f.collection_select :playlist_id, current_user.playlists, :id, :name, { prompt: "Select your playlist" }, class: "form-control" %>
              <%= f.hidden_field :song_id, id: "modalSongId", data: { modal_target: "songIdInput" } %>
              <%= f.submit class:"btn-app mt-3", value: "Add to my playlist" %>
            <% end %>
          </div>
        </div>
      <% else %>
        <div class="modal-header text-center">
          <p>You don't have any playlist yet, create one: </p>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <%= render "playlists/new" %>
      <% end %>
      <div class="modal-footer"></div>
    </div>
  </div>
</div>

</div>

<script src="https://sdk.scdn.co/spotify-player.js"></script>
<script>
   if (sessionStorage.getItem('pageLoadedBefore')) {
  // If so, reload the page
  sessionStorage.removeItem('pageLoadedBefore');
  window.location.reload();
} else {
  // If not, set the flag in sessionStorage
  sessionStorage.setItem('pageLoadedBefore', true);
}

  document.addEventListener('DOMContentLoaded', function() {
  let player; // Declare player globally
  let playbackPosition; // Variable to store playback position

  // Function to play track
  function playTrack(trackId) {
    const token = document.getElementById("access-token").dataset.token;
    player = new Spotify.Player({
      name: 'Web Playback SDK Quick Start Player',
      getOAuthToken: cb => { cb(token); },
      volume: 0.5,
      robustnessLevel: 'MID'
    });

    // Play the track
    player.addListener('ready', ({ device_id }) => {
      console.log('Ready with Device ID', device_id);
      playTrackOnDevice(device_id, trackId);
    });

    player.connect();
  }

  // Function to play track on the device
  function playTrackOnDevice(deviceId, trackId) {
    const token = document.getElementById("access-token").dataset.token;
    fetch(`https://api.spotify.com/v1/me/player/play?device_id=${deviceId}`, {
      method: 'PUT',
      body: JSON.stringify({
        uris: [`spotify:track:${trackId}`],
        position_ms: playbackPosition // Set playback position
      }),
      headers: {
        'Content-Type': 'application/json',
        'Authorization': `Bearer ${token}`
      },
    });
  }

  // Function to pause track
  function pauseTrack() {
    player.getCurrentState().then(state => {
      if (state) {
        playbackPosition = state.position; // Store playback position
        player.pause();
      }
    });
  }

  // Define a global variable to store the currently playing track ID
let currentlyPlayingTrackId = null;


// Event listener for play/pause button
const playButton = document.querySelector('.play-btn');
playButton.addEventListener('click', function() {
  const trackId = document.querySelector(".track-title-player").dataset.albumTrackId;
  const isPlaying = this.dataset.playing === 'true';

  // Check if the current track is already playing
  const isCurrentTrackPlaying = trackId === currentlyPlayingTrackId;

  if (isPlaying) {
    // Pause the track only if it's the currently playing track
    if (isCurrentTrackPlaying) {
      pauseTrack();
    }
    this.dataset.playing = 'false';
    this.innerHTML = '<i class="fa-solid fa-play"></i>';
  } else {
    // Play the track from the beginning if it's a new track
    if (!isCurrentTrackPlaying) {
      playbackPosition = 0; // Start from the beginning
    }
    playTrack(trackId);
    currentlyPlayingTrackId = trackId; // Update currentlyPlayingTrackId
    this.dataset.playing = 'true';
    this.innerHTML = '<i class="fa-solid fa-pause"></i>';
  }
});


  // Spotify Web Playback SDK initialization
  window.onSpotifyWebPlaybackSDKReady = () => {
    const token = document.getElementById("access-token").dataset.token;
    player = new Spotify.Player({
      name: 'Web Playback SDK Quick Start Player',
      getOAuthToken: cb => { cb(token); },
      volume: 0.5
    });

    // Ready
    player.addListener('ready', ({ device_id }) => {
      console.log('Ready with Device ID', device_id);
    });

    // Not Ready
    player.addListener('not_ready', ({ device_id }) => {
      console.log('Device ID has gone offline', device_id);
    });

    player.addListener('initialization_error', ({ message }) => {
      console.error(message);
    });

    player.addListener('authentication_error', ({ message }) => {
      console.error(message);
    });

    player.addListener('account_error', ({ message }) => {
      console.error(message);
    });

    player.connect();
  };
});
</script>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_header.html.erb
<div class="header">
  <div class="logo">
      <%= image_tag "logo.png"%>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="nav-wrapper">
  <div class="icon-bar">

    <%= link_to root_path do %>
      <i class="fa-solid fa-house"></i>
    <% end %>

    <%= link_to shows_path do %>
      <i class="fa-solid fa-masks-theater"></i>
    <% end %>

    <%= link_to selected_shows_path do %>
      <i class="fa-regular fa-heart"></i>
    <% end %>


    <%= link_to playlists_path do %>
      <i class="fa-solid fa-music"></i>
    <% end %>
  </div>
</div>

app/views/shows/index.html.erb
<div class="search-bar-container d-flex justify-content-center my-3">
  <%= form_tag shows_path, method: :get, class: "search-bar" do %>
      <%= text_field_tag :search, params[:search], placeholder: "Search for a show", class: "search-input", autocomplete: "off" %>
      <%= button_tag type: 'submit', class: "search-button" do %>
        <i class="fa-solid fa-magnifying-glass"></i>
      <% end %>
    <% end %>
</div>

<div data-controller="show-modal" >
  <div class="cards-container mb-3" >
    <% @shows.each do |show| %>
      <div class="card-show d-flex p-3">
        <div class="card-img w-50">
          <%= image_tag show.image_url, alt: "#{show.title} Image", class: "show-image" %>
        </div>
        <div class="card-info w-50">
          <div class="card-title d-flex justify-content-between">
            <h3><strong><%= show.title %></strong></h3>
            <% unless SelectedShow.where(show_id: show.id, user_id: current_user.id).exists? %>
              <%= link_to selected_shows_path(selected_show: { user_id: current_user.id, show_id: show.id }), data: { 'turbo-method' => :post } do %>
                <i class="fa-solid fa-heart favorite" aria-label="Add to favorites"></i>
              <% end %>
            <% end %>
          </div>
          <%= show.description.truncate(80, separator: ' ', omission: '...') %>
          <button type="button" class="btn-read-more mt-3" data-bs-toggle="modal" data-bs-target="#showModal" data-show-modal-target="button" data-action="click->show-modal#open" data-show-title="<%= show.title %>" data-show-content="<%= show.description %>">
            <i class="fa-solid fa-angles-right"></i>
          </button>
        </div>
      </div>
    <% end %>
  </div>

  <div class="modal fade" id="showModal" tabindex="-1" aria-labelledby="showModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header text-center" >
        <p class="modal-show-title w-75"><span id="modalShowTitle" data-show-modal-target="title"></span> </p>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body content" data-show-modal-target="content">

      </div>
      <div class="modal-footer"></div>
    </div>
  </div>
  </div>
</div>